controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:   # [TODO]: Faire fonctionner le controller SecurityController.php et la route "/api/login".
    path: /auth
    methods: ['POST']